### ISSUE TITLE
Some problems with glazed terracottas

### ISSUE THREAD

**Issue by NikkeDoy** [SkriptLang/skript-aliases#34]
So the problem is if i want to check if player has red (or other color) glazed terracotta.
Skript doesn't know what red glazed terracotta is.

I tested this by looping all items in my inventory and saying what is it.
![image](https://user-images.githubusercontent.com/42248504/48314431-1996b480-e5d2-11e8-8bd5-9da3a9b97fe1.png)

This is pretty weird right?

**Comment by TheBentoBox** [comment]
This is a known issue, blocks in the inventory can show block state as if they were placed. I don't believe there's anything I can do in the aliases themselves to address this.

In regards to not being able to reference red glazed terracotta, I can't reproduce your issue:
![image](https://user-images.githubusercontent.com/6902229/48316679-104b1f00-e5b5-11e8-9b61-86c7a52fc322.png)

This made me realize that there is no `any glazed terracotta`, so I'll add that now, but otherwise I believe this an issue in your script with referring to the alias incorrectly.
