### ISSUE TITLE
1.9 support

### ISSUE THREAD

**Issue by bensku** [SkriptLang/skript-aliases#36]
Minecraft 1.9 has a ton of issues with current aliases. See error log: https://gist.github.com/bensku/de6a8f1212a13d76050e63b38666a05c

In particular, stationary water alias does not seem to work, which causes Skript fail to start.

**Comment by TheBentoBox** [comment]
This isn't actually too bad since it's largely repetitions of the same aliases due to the many patterns available to them, so it's probably just due to an alias accidentally not being registered simply due to being missed, or potentially being registered with the wrong MC ID. I'll take a look at these tonight.

**Comment by bensku** [comment]
Thanks! If you encounter problems that might be Skript bugs, let me know.

**Comment by bensku** [comment]
I added real material mappings for 1.9. Interestingly enough, it seems that there is a Spigot bug which causes modifyItemStack to throw NPE. Still, it looks like there are a few ordinary alias issues that you could look at.

**Comment by Snow-Pyon** [comment]
I feel like this was already fixed so, this could be closed now I guess.
